### ISSUE TITLE
some standard dfhack functions aren't recognized

### ISSUE THREAD

**Issue by TimurKelman** [vallode/dfhack-lua-definitions#1]
`print_all` is recognized but doesn't exist in DFHack, while `printall` does exist but isn't recognized.

**Comment by vallode** [comment]
Interestingly enough neither are actually defined in these files. Added printall and printall_recursive in 1ca380120ab9856a1eb1c0c38ad9a298f53c6496. I think `print_all` is being suggested due to it's existence in the `prechange.lua` script, nothing I can do about that.

Thanks for reporting this :)
